#define CHAR_HEIGHT 14
#define Y_OFFSET 3
#define ROW_HEIGHT 15

				//(x, y, w, h)
#define BATTERY GRect(7,(0 * ROW_HEIGHT) + Y_OFFSET,75,CHAR_HEIGHT)
#define ITS GRect(83,(0 * ROW_HEIGHT) + Y_OFFSET,33,CHAR_HEIGHT)
#define AT GRect(117,(0 * ROW_HEIGHT) + Y_OFFSET,19,CHAR_HEIGHT)
	
#define QUARTER GRect(11,(1 * ROW_HEIGHT) + Y_OFFSET,79,CHAR_HEIGHT)
#define HALF GRect(91,(1 * ROW_HEIGHT) + Y_OFFSET,42,CHAR_HEIGHT)
	
#define TWENTY GRect(1,(2 * ROW_HEIGHT) + Y_OFFSET,70,CHAR_HEIGHT)
#define TWENTYFIVE GRect(1,(2 * ROW_HEIGHT) + Y_OFFSET,109,CHAR_HEIGHT)
#define FIVE_M GRect(72,(2 * ROW_HEIGHT) + Y_OFFSET,38,CHAR_HEIGHT)
#define TEN_M GRect(111,(2 * ROW_HEIGHT) + Y_OFFSET,32,CHAR_HEIGHT)
	
#define PAST GRect(3,(3 * ROW_HEIGHT) + Y_OFFSET,42,CHAR_HEIGHT)
#define TO GRect(36,(3 * ROW_HEIGHT) + Y_OFFSET,22,CHAR_HEIGHT)
#define FIFTY GRect(59,(3 * ROW_HEIGHT) + Y_OFFSET,47,CHAR_HEIGHT)
#define TEN_H GRect(109,(3 * ROW_HEIGHT) + Y_OFFSET,32,CHAR_HEIGHT)
	
#define ONE GRect(2,(4 * ROW_HEIGHT) + Y_OFFSET,35,CHAR_HEIGHT)
#define NINE GRect(38,(4 * ROW_HEIGHT) + Y_OFFSET,43,CHAR_HEIGHT)
#define NINETY GRect(38,(4 * ROW_HEIGHT) + Y_OFFSET,65,CHAR_HEIGHT)
#define TWO GRect(104,(4 * ROW_HEIGHT) + Y_OFFSET,38,CHAR_HEIGHT)
	
#define THREE GRect(7,(5 * ROW_HEIGHT) + Y_OFFSET,53,CHAR_HEIGHT)
#define SEVEN GRect(61,(5 * ROW_HEIGHT) + Y_OFFSET,54,CHAR_HEIGHT)
#define SEVENTY GRect(61,(5 * ROW_HEIGHT) + Y_OFFSET,76,CHAR_HEIGHT)
	
#define ELEVEN GRect(7,(6 * ROW_HEIGHT) + Y_OFFSET,63,CHAR_HEIGHT)
#define TWELVE GRect(71,(6 * ROW_HEIGHT) + Y_OFFSET,66,CHAR_HEIGHT)
	
#define FORTY GRect(2,(7 * ROW_HEIGHT) + Y_OFFSET,56,CHAR_HEIGHT)
#define HUNDRED GRect(59,(7 * ROW_HEIGHT) + Y_OFFSET,82,CHAR_HEIGHT)
	
#define FIVE_H GRect(2,(8 * ROW_HEIGHT) + Y_OFFSET,38,CHAR_HEIGHT)
#define EIGHT GRect(31,(8 * ROW_HEIGHT) + Y_OFFSET,51,CHAR_HEIGHT)
#define EIGHTY GRect(31,(8 * ROW_HEIGHT) + Y_OFFSET,63,CHAR_HEIGHT)
#define FOUR GRect(95,(8 * ROW_HEIGHT) + Y_OFFSET,46,CHAR_HEIGHT)
	
#define SIX GRect(5,(9 * ROW_HEIGHT) + Y_OFFSET,29,CHAR_HEIGHT)
#define SIXTY GRect(5,(9 * ROW_HEIGHT) + Y_OFFSET,51,CHAR_HEIGHT)
#define O GRect(57,(9 * ROW_HEIGHT) + Y_OFFSET,18,CHAR_HEIGHT)
#define THIRTY GRect(75,(9 * ROW_HEIGHT) + Y_OFFSET,63,CHAR_HEIGHT)
	
#define PERCENT GRect(6,(10 * ROW_HEIGHT) + Y_OFFSET,76,CHAR_HEIGHT)
#define CLOCK GRect(83,(10 * ROW_HEIGHT) + Y_OFFSET,55,CHAR_HEIGHT)